# Generated by Django 5.2.8 on 2025-11-23 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'verbose_name': 'My Profile', 'verbose_name_plural': 'My Profile'},
        ),
    ]
